export interface CONFIG {
  MONGO_USERNAME: string;
  MONGO_PASSOWRD: string;
  MONGO_SERVER: string;
  CHAT_SERVER_PORT: number;
  MONGO_DB_NAME: string;
  CHAT_SERVER_ENV: string;
  MONGODB_CONNECTION_STRING: string;
  MONGODB_CONNECTION_STRING_LOGGER:string;
}
