export interface ICONFIG {
  MONGO_USERNAME: string;
  MONGO_PASSOWRD: string;
  MONGO_SERVER: string;
  CHAT_SERVER_PORT: number;
  MONGO_DB_NAME: string;
  CHAT_SERVER_ENV: string;
  MONGODB_CONNECTION_STRING: string;
  MONGODB_CONNECTION_STRING_LOGGER:string;
  DEBUG:boolean;
  CHAT_SERVER_JWT_SECRET:string;
  CHAT_SERVER_JWT_EXPIRE_IN_MINUTE:number;
}
